import dynamic from 'next/dynamic';
import { content, whatsappLink } from '@/lib/content';

const CoffeeJourney = dynamic(() => import('@/components/CoffeeJourney'), { ssr: false, loading: () => <div className="scene-fallback" aria-label="Coffee plant scene loading" /> });

const journey = [
  ['01', 'It begins with the plant.', 'Every exceptional cup starts with the quality of what grows at its origin.'],
  ['02', 'Beauty before the bean.', 'Coffee begins as a fruit — vivid, seasonal and alive.'],
  ['03', 'Where character develops.', 'Careful stages shape the aroma, balance and depth in every cup.'],
  ['04', 'The moment aroma comes alive.', 'Roasted beans become a daily ritual, one considered detail at a time.']
];

export default function Home() {
  const orderLink = whatsappLink('Hi SAISTA COFFEE, I’d like to place an order.');
  return <main>
    <div className="demo-bar">{content.demoNotice}<span>All origin, process and story details are placeholders.</span></div>
    <nav className="nav"><a className="wordmark" href="#top">SAISTA <i>COFFEE</i></a><div className="nav-links"><a href="#journey">Journey</a><a href="#shop">Shop</a><a href="#story">Our Story</a><a href="#contact">Contact</a></div><a className="nav-cta" href={orderLink} target="_blank" rel="noreferrer">Order Coffee <span>↗</span></a></nav>
    <section id="top" className="hero"><div className="hero-image" /><div className="hero-content"><p className="eyebrow">A coffee journey · Coorg, Karnataka <sup>DEMO</sup></p><h1>From nature,<br /><em>to your cup.</em></h1><p className="hero-copy">Discover coffee crafted with respect for where it begins.</p><div className="hero-actions"><a className="button button-light" href="#journey">Explore the journey <span>↓</span></a><a className="text-link" href="#shop">Shop coffee <span>↗</span></a></div></div><div className="hero-scene"><CoffeeJourney /></div><div className="scroll-cue"><span>Scroll to explore</span><b>↓</b></div></section>
    <section id="journey" className="journey-intro"><p className="eyebrow">The coffee journey</p><h2>A cup is never<br /><em>just a cup.</em></h2><p>It is a passage through soil, seasons, fruit, patience and craft. Follow coffee from its natural beginning to the moment it becomes yours.</p></section>
    <section className="journey-scenes">{journey.map(([number, title, copy], index) => <article className={`journey-scene scene-${index + 1}`} key={number}><div className="scene-visual"><div className="scene-number">{number}</div><div className="scene-orb" /><span className="visual-label">PLACEHOLDER VISUAL — REPLACE WITH BRAND PHOTOGRAPHY</span></div><div className="scene-copy"><p className="eyebrow">Chapter {number}</p><h3>{title}</h3><p>{copy}</p></div></article>)}</section>
    <section id="shop" className="shop"><div className="section-head"><div><p className="eyebrow">The collection</p><h2>Meet your<br /><em>daily ritual.</em></h2></div><a className="text-link" href={orderLink} target="_blank" rel="noreferrer">Order on WhatsApp <span>↗</span></a></div><div className="product-grid">{content.products.map(product => <article className="product-card" key={product.id}><div className="product-image" style={{ backgroundImage: `url(${product.image})` }}><span>PLACEHOLDER IMAGE</span><button aria-label={`Quick view ${product.name}`}>Quick view ↗</button></div><div className="product-meta"><div><p className="eyebrow">{product.type} · {product.roast}</p><h3>{product.name}</h3><p className="notes">{product.notes}</p></div><strong>{product.price}</strong></div><a className="product-order" href={whatsappLink(`Hi SAISTA COFFEE, I’d like to order ${product.name} — ${product.weight}.`)} target="_blank" rel="noreferrer">Add to order <span>↗</span></a></article>)}</div></section>
    <section id="story" className="story"><div className="story-photo"><div><p className="eyebrow">The story</p><h2>Good coffee<br /><em>has a story.</em></h2></div><span>PLACEHOLDER IMAGE — REPLACE WITH BRAND PHOTOGRAPHY</span></div><div className="story-copy"><p className="eyebrow">A note from SAISTA</p><p className="large-copy">Great coffee should take you closer to where it comes from.</p><p>From the green coffee plant to the final cup, every stage is an opportunity to preserve character, aroma and craft.</p><p className="placeholder-note">[FOUNDER STORY — REPLACE WITH VERIFIED BRAND STORY]</p></div></section>
    <section className="final-cta"><p className="eyebrow">From nature, to your cup</p><h2>Ready for your<br /><em>next cup?</em></h2><p>Discover coffee from its natural beginning to your daily ritual.</p><div className="hero-actions"><a className="button button-light" href="#shop">Shop coffee <span>↗</span></a><a className="button button-outline" href={orderLink} target="_blank" rel="noreferrer">Order on WhatsApp <span>↗</span></a></div></section>
    <footer id="contact"><div className="footer-top"><a className="wordmark" href="#top">SAISTA <i>COFFEE</i></a><p>Stay close to the coffee journey.</p><form><label className="sr-only" htmlFor="email">Email address</label><input id="email" type="email" placeholder="Your email address" /><button type="submit">Subscribe ↗</button></form></div><div className="footer-bottom"><span>© 2026 SAISTA COFFEE · DEMO EXPERIENCE</span><div><a href="#story">Our Story</a><a href="#shop">Shop</a><a href={orderLink} target="_blank" rel="noreferrer">WhatsApp</a><a href="#top">Back to top ↑</a></div></div></footer><a className="mobile-order" href={orderLink} target="_blank" rel="noreferrer">Order on WhatsApp <span>↗</span></a>
  </main>;
}
