'use client';

import dynamic from 'next/dynamic';
import { useMemo, useState } from 'react';
import { content, whatsappLink } from '@/lib/content';

const JourneyExperience = dynamic(() => import('@/components/JourneyExperience'), {
  ssr: false,
  loading: () => <div className="journey-loader" aria-label="Loading the coffee journey" />,
});

type Filter = 'All' | 'Light Roast' | 'Medium Roast' | 'Dark Roast' | 'Ground' | 'Whole Bean';

export default function Home() {
  const [filter, setFilter] = useState<Filter>('All');
  const [quizStep, setQuizStep] = useState(0);
  const [quizAnswer, setQuizAnswer] = useState('');
  const [quickView, setQuickView] = useState<(typeof content.products)[number] | null>(null);
  const filters: Filter[] = ['All', 'Light Roast', 'Medium Roast', 'Dark Roast', 'Ground', 'Whole Bean'];
  const filteredProducts = useMemo(() => content.products.filter((product) => filter === 'All' || product.roast === filter || product.format === filter), [filter]);
  const orderLink = whatsappLink('Hi SAISTA COFFEE, I’d like to place an order.');
  const quizRecommendation = quizAnswer === 'Bold' ? content.products[2] : quizAnswer === 'Smooth' ? content.products[3] : content.products[1];

  return <main>
    <div className="demo-bar">{content.demoNotice}<span>All origin, process and story details are placeholders.</span></div>
    <nav className="nav"><a className="wordmark" href="#top">SAISTA <i>COFFEE</i></a><div className="nav-links"><a href="#journey">Journey</a><a href="#shop">Shop</a><a href="#story">Our Story</a><a href="#contact">Contact</a></div><a className="nav-cta" href={orderLink} target="_blank" rel="noreferrer">Order Coffee <span>↗</span></a></nav>

    <section id="top" className="hero"><div className="hero-image" /><div className="hero-content"><p className="eyebrow">A coffee journey · Coorg, Karnataka <sup>DEMO</sup></p><h1>From nature,<br /><em>to your cup.</em></h1><p className="hero-copy">Discover coffee crafted with respect for where it begins.</p><div className="hero-actions"><a className="button button-light" href="#journey">Explore the journey <span>↓</span></a><a className="text-link" href="#shop">Shop coffee <span>↗</span></a></div></div><div className="hero-scene"><JourneyExperience /></div><div className="scroll-cue"><span>Scroll to explore</span><b>↓</b></div></section>

    <section id="journey" className="journey-wrap"><div className="journey-intro"><p className="eyebrow">The coffee journey</p><h2>A cup is never<br /><em>just a cup.</em></h2><p>It is a passage through soil, seasons, fruit, patience and craft. Scroll through coffee from its natural beginning to the moment it becomes yours.</p></div><div className="story-stage"><JourneyExperience /><div className="journey-copy"><p className="eyebrow">Scroll narrative · <span className="journey-progress">Nature</span></p><h2 className="journey-title">It begins<br /><em>with the plant.</em></h2><p className="journey-description">Every exceptional cup starts with the quality of what grows at its origin.</p></div><div className="journey-chapters">{['Nature','Cherry','Bean','Process','Roast','Grind','Brew','Cup'].map((chapter, i) => <a href={`#chapter-${i}`} key={chapter}><span>0{i + 1}</span>{chapter}</a>)}</div></div></section>

    <section id="shop" className="shop"><div className="section-head"><div><p className="eyebrow">The collection</p><h2>Meet your<br /><em>daily ritual.</em></h2></div><a className="text-link" href={orderLink} target="_blank" rel="noreferrer">Order on WhatsApp <span>↗</span></a></div><div className="filters" role="group" aria-label="Filter coffee products">{filters.map(item => <button className={filter === item ? 'active' : ''} onClick={() => setFilter(item)} key={item}>{item}</button>)}</div><div className="product-grid">{filteredProducts.map(product => <article className="product-card" key={product.id}><div className="product-image" style={{ backgroundImage: `url(${product.image})` }}><span>PLACEHOLDER IMAGE</span><button onClick={() => setQuickView(product)} aria-label={`Quick view ${product.name}`}>Quick view ↗</button></div><div className="product-meta"><div><p className="eyebrow">{product.type} · {product.roast}</p><h3>{product.name}</h3><p className="notes">{product.notes}</p></div><strong>{product.price}</strong></div><a className="product-order" href={whatsappLink(`Hi SAISTA COFFEE, I’d like to order ${product.name} — ${product.weight}.`)} target="_blank" rel="noreferrer">Add to order <span>↗</span></a></article>)}</div></section>

    <section className="finder"><div><p className="eyebrow">A considered recommendation</p><h2>Find your<br /><em>coffee.</em></h2><p>Two quick choices. One better daily ritual.</p></div><div className="quiz-panel">{quizStep === 0 ? <><p className="quiz-question">How do you like your coffee?</p><div className="quiz-options">{['Smooth','Balanced','Bold'].map(answer => <button onClick={() => { setQuizAnswer(answer); setQuizStep(1); }} key={answer}>{answer}<span>↗</span></button>)}</div></> : quizStep === 1 ? <><p className="quiz-question">How do you brew?</p><div className="quiz-options">{['Espresso','French Press','Pour Over','Moka','Other'].map(answer => <button onClick={() => setQuizStep(2)} key={answer}>{answer}<span>↗</span></button>)}</div></> : <div className="recommendation"><p className="eyebrow">Your match</p><h3>{quizRecommendation.name}</h3><p>{quizRecommendation.notes}</p><a className="button button-dark" href={whatsappLink(`Hi SAISTA COFFEE, I’d like to order ${quizRecommendation.name} — ${quizRecommendation.weight}.`)} target="_blank" rel="noreferrer">Order your match <span>↗</span></a><button className="restart" onClick={() => { setQuizStep(0); setQuizAnswer(''); }}>Start again</button></div>}</div></section>

    <section id="story" className="story"><div className="story-photo"><div><p className="eyebrow">The story</p><h2>Good coffee<br /><em>has a story.</em></h2></div><span>PLACEHOLDER IMAGE — REPLACE WITH BRAND PHOTOGRAPHY</span></div><div className="story-copy"><p className="eyebrow">A note from SAISTA</p><p className="large-copy">Great coffee should take you closer to where it comes from.</p><p>From the green coffee plant to the final cup, every stage is an opportunity to preserve character, aroma and craft.</p><p className="placeholder-note">[FOUNDER STORY — REPLACE WITH VERIFIED BRAND STORY]</p><div className="quality-grid">{content.quality.map(item => <div key={item.title}><b>{item.title}</b><span>{item.description}</span></div>)}</div></div></section>

    <section className="proof"><p className="eyebrow">Notes from the ritual · Demo content</p><div className="proof-grid">{content.testimonials.map(item => <blockquote key={item.quote}><span>★★★★★</span><p>“{item.quote}”</p><cite>— {item.author}</cite></blockquote>)}</div></section>
    <section className="final-cta"><p className="eyebrow">From nature, to your cup</p><h2>Ready for your<br /><em>next cup?</em></h2><p>Discover coffee from its natural beginning to your daily ritual.</p><div className="hero-actions"><a className="button button-light" href="#shop">Shop coffee <span>↗</span></a><a className="button button-outline" href={orderLink} target="_blank" rel="noreferrer">Order on WhatsApp <span>↗</span></a></div></section>
    <footer id="contact"><div className="footer-top"><a className="wordmark" href="#top">SAISTA <i>COFFEE</i></a><p>Stay close to the coffee journey.</p><form onSubmit={(event) => event.preventDefault()}><label className="sr-only" htmlFor="email">Email address</label><input id="email" type="email" placeholder="Your email address" /><button type="submit">Subscribe ↗</button></form></div><div className="footer-bottom"><span>© 2026 SAISTA COFFEE · DEMO EXPERIENCE</span><div><a href="#story">Our Story</a><a href="#shop">Shop</a><a href={orderLink} target="_blank" rel="noreferrer">WhatsApp</a><a href="#top">Back to top ↑</a></div></div></footer><a className="mobile-order" href={orderLink} target="_blank" rel="noreferrer">Order on WhatsApp <span>↗</span></a>
    {quickView && <div className="modal-backdrop" role="presentation" onClick={() => setQuickView(null)}><div className="quick-modal" role="dialog" aria-modal="true" aria-label={`${quickView.name} quick view`} onClick={event => event.stopPropagation()}><button className="modal-close" onClick={() => setQuickView(null)} aria-label="Close">×</button><div className="modal-image" style={{ backgroundImage: `url(${quickView.image})` }} /><div className="modal-info"><p className="eyebrow">{quickView.type} · {quickView.roast}</p><h3>{quickView.name}</h3><p>{quickView.notes}</p><strong>{quickView.price} · {quickView.weight}</strong><a className="button button-dark" href={whatsappLink(`Hi SAISTA COFFEE, I’d like to order ${quickView.name} — ${quickView.weight}.`)} target="_blank" rel="noreferrer">Order on WhatsApp <span>↗</span></a></div></div></div>}
  </main>;
}
